package profanity

import (
	"regexp"
	"strings"
)

// ContainsProfanity returns true if the provided input is profane, or contains profanity
// This is not really an exhaustive check, it's just there to catch obvious rudeness, and as
// a proof of concept.
func ContainsProfanity(input string) bool {
	inputLower := strings.ToLower(input)

	for _, pattern := range badwords {
		if pattern.MatchString(inputLower) {
			return true
		}
	}

	return false
}

// A very simple slice of regex patterns that are designed to catch only the most basic rude words
// The english list is pretty small, I feel like nowadays we are pretty blaise about swearing.
// Besides if there was a username reporting system, people could just use that.
// For japanese, the source here: https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/blob/master/ja
// was taken in it's entirety - most of them seem fine, some seem a bit strict but I was raised abroad so I don't
// really have any way of knowing the severity of these words
var badwords = []*regexp.Regexp{
	// EN
	regexp.MustCompile(`piss`),
	regexp.MustCompile(`shit`),
	regexp.MustCompile(`fuck`),
	regexp.MustCompile(`cunt`),
	regexp.MustCompile(`motherfucker`),
	regexp.MustCompile(`mother fucker`),
	regexp.MustCompile(`gash`),
	regexp.MustCompile(`minge`),
	regexp.MustCompile(`twat`),
	regexp.MustCompile(`rape`),

	// JP
	regexp.MustCompile(`3p`),
	regexp.MustCompile(`g スポット`),
	regexp.MustCompile(`s ＆ m`),
	regexp.MustCompile(`sm`),
	regexp.MustCompile(`sm女王`),
	regexp.MustCompile(`xx`),
	regexp.MustCompile(`アジアのかわいい女の子`),
	regexp.MustCompile(`アスホール`),
	regexp.MustCompile(`アナリングス`),
	regexp.MustCompile(`アナル`),
	regexp.MustCompile(`いたずら`),
	regexp.MustCompile(`イラマチオ`),
	regexp.MustCompile(`ウェブカメラ`),
	regexp.MustCompile(`エクスタシー`),
	regexp.MustCompile(`エスコート`),
	regexp.MustCompile(`エッチ`),
	regexp.MustCompile(`エロティズム`),
	regexp.MustCompile(`エロティック`),
	regexp.MustCompile(`オーガズム`),
	regexp.MustCompile(`オカマ`),
	regexp.MustCompile(`おしっこ`),
	regexp.MustCompile(`おしり`),
	regexp.MustCompile(`オシリ`),
	regexp.MustCompile(`おしりのあな`),
	regexp.MustCompile(`おっぱい`),
	regexp.MustCompile(`オッパイ`),
	regexp.MustCompile(`オナニー`),
	regexp.MustCompile(`オマンコ`),
	regexp.MustCompile(`おもらし`),
	regexp.MustCompile(`お尻`),
	regexp.MustCompile(`カーマスートラ`),
	regexp.MustCompile(`カント`),
	regexp.MustCompile(`クリトリス`),
	regexp.MustCompile(`グループ・セックス`),
	regexp.MustCompile(`グロ`),
	regexp.MustCompile(`クンニリングス`),
	regexp.MustCompile(`ゲイ・セックス`),
	regexp.MustCompile(`ゲイの男性`),
	regexp.MustCompile(`ゲイボーイ`),
	regexp.MustCompile(`ゴールデンシャワー`),
	regexp.MustCompile(`コカイン`),
	regexp.MustCompile(`ゴックン`),
	regexp.MustCompile(`サディズム`),
	regexp.MustCompile(`しばり`),
	regexp.MustCompile(`スウィンガー`),
	regexp.MustCompile(`スカートの中`),
	regexp.MustCompile(`スカトロ`),
	regexp.MustCompile(`ストラップオン`),
	regexp.MustCompile(`ストリップ劇場`),
	regexp.MustCompile(`スラット`),
	regexp.MustCompile(`スリット`),
	regexp.MustCompile(`セクシーな`),
	regexp.MustCompile(`セクシーな 10 代`),
	regexp.MustCompile(`セックス`),
	regexp.MustCompile(`ソドミー`),
	regexp.MustCompile(`ちんこ`),
	regexp.MustCompile(`ディープ・スロート`),
	regexp.MustCompile(`ディック`),
	regexp.MustCompile(`ディルド`),
	regexp.MustCompile(`デートレイプ`),
	regexp.MustCompile(`デブ`),
	regexp.MustCompile(`テレフォンセックス`),
	regexp.MustCompile(`ドッグスタイル`),
	regexp.MustCompile(`トップレス`),
	regexp.MustCompile(`なめ`),
	regexp.MustCompile(`ニガー`),
	regexp.MustCompile(`ヌード`),
	regexp.MustCompile(`ネオ・ナチ`),
	regexp.MustCompile(`ハードコア`),
	regexp.MustCompile(`パイパン`),
	regexp.MustCompile(`バイブレーター`),
	regexp.MustCompile(`バック・スタイル`),
	regexp.MustCompile(`パンティー`),
	regexp.MustCompile(`ビッチ`),
	regexp.MustCompile(`ファック`),
	regexp.MustCompile(`ファンタジー`),
	regexp.MustCompile(`フィスト`),
	regexp.MustCompile(`フェティッシュ`),
	regexp.MustCompile(`フェラチオ`),
	regexp.MustCompile(`ふたなり`),
	regexp.MustCompile(`ぶっかけ`),
	regexp.MustCompile(`フック`),
	regexp.MustCompile(`プリンス アルバート ピアス`),
	regexp.MustCompile(`プレイボーイ`),
	regexp.MustCompile(`ベアバック`),
	regexp.MustCompile(`ペニス`),
	regexp.MustCompile(`ペニスバンド`),
	regexp.MustCompile(`ボーイズラブ`),
	regexp.MustCompile(`ボールギャグ`),
	regexp.MustCompile(`ボールを蹴る`),
	regexp.MustCompile(`ぽっちゃり`),
	regexp.MustCompile(`ホモ`),
	regexp.MustCompile(`ポルノ`),
	regexp.MustCompile(`ポルノグラフィー`),
	regexp.MustCompile(`ボンテージ`),
	regexp.MustCompile(`マザー・ファッカー`),
	regexp.MustCompile(`マスターベーション`),
	regexp.MustCompile(`まんこ`),
	regexp.MustCompile(`やおい`),
	regexp.MustCompile(`やりまん`),
	regexp.MustCompile(`ユダヤ人`),
	regexp.MustCompile(`ラティーナ`),
	regexp.MustCompile(`ラバー`),
	regexp.MustCompile(`ランジェリー`),
	regexp.MustCompile(`レイプ`),
	regexp.MustCompile(`レズビアン`),
	regexp.MustCompile(`ローター`),
	regexp.MustCompile(`ロリータ`),
	regexp.MustCompile(`淫乱`),
	regexp.MustCompile(`陰毛`),
	regexp.MustCompile(`革抑制`),
	regexp.MustCompile(`騎上位`),
	regexp.MustCompile(`巨根`),
	regexp.MustCompile(`巨乳`),
	regexp.MustCompile(`強姦犯`),
	regexp.MustCompile(`玉なめ`),
	regexp.MustCompile(`玉舐め`),
	regexp.MustCompile(`緊縛`),
	regexp.MustCompile(`近親相姦`),
	regexp.MustCompile(`嫌い`),
	regexp.MustCompile(`後背位`),
	regexp.MustCompile(`合意の性交`),
	regexp.MustCompile(`拷問`),
	regexp.MustCompile(`殺し方`),
	regexp.MustCompile(`殺人事件`),
	regexp.MustCompile(`殺人方法`),
	regexp.MustCompile(`支配`),
	regexp.MustCompile(`児童性虐待`),
	regexp.MustCompile(`自己愛性`),
	regexp.MustCompile(`射精`),
	regexp.MustCompile(`手コキ`),
	regexp.MustCompile(`獣姦`),
	regexp.MustCompile(`女の子`),
	regexp.MustCompile(`女王様`),
	regexp.MustCompile(`女子高生`),
	regexp.MustCompile(`女装`),
	regexp.MustCompile(`新しいポルノ`),
	regexp.MustCompile(`人妻`),
	regexp.MustCompile(`人種`),
	regexp.MustCompile(`性交`),
	regexp.MustCompile(`正常位`),
	regexp.MustCompile(`生殖器`),
	regexp.MustCompile(`精液`),
	regexp.MustCompile(`挿入`),
	regexp.MustCompile(`足フェチ`),
	regexp.MustCompile(`足を広げる`),
	regexp.MustCompile(`大陰唇`),
	regexp.MustCompile(`脱衣`),
	regexp.MustCompile(`茶色のシャワー`),
	regexp.MustCompile(`中出し`),
	regexp.MustCompile(`潮吹き女`),
	regexp.MustCompile(`潮吹き男性`),
	regexp.MustCompile(`直腸`),
	regexp.MustCompile(`剃毛`),
	regexp.MustCompile(`貞操帯`),
	regexp.MustCompile(`奴隷`),
	regexp.MustCompile(`二穴`),
	regexp.MustCompile(`乳首`),
	regexp.MustCompile(`尿道プレイ`),
	regexp.MustCompile(`覗き`),
	regexp.MustCompile(`売春婦`),
	regexp.MustCompile(`縛り`),
	regexp.MustCompile(`噴出`),
	regexp.MustCompile(`糞`),
	regexp.MustCompile(`糞尿愛好症`),
	regexp.MustCompile(`糞便`),
	regexp.MustCompile(`平手打ち`),
	regexp.MustCompile(`変態`),
	regexp.MustCompile(`勃起する`),
	regexp.MustCompile(`夢精`),
	regexp.MustCompile(`毛深い`),
	regexp.MustCompile(`誘惑`),
	regexp.MustCompile(`幼児`),
	regexp.MustCompile(`幼児性愛者`),
	regexp.MustCompile(`裸`),
	regexp.MustCompile(`裸の女性`),
	regexp.MustCompile(`乱交`),
	regexp.MustCompile(`両性`),
	regexp.MustCompile(`両性具有`),
	regexp.MustCompile(`両刀`),
	regexp.MustCompile(`輪姦`),
	regexp.MustCompile(`卍`),
	regexp.MustCompile(`宦官`),
	regexp.MustCompile(`肛門`),
	regexp.MustCompile(`膣`),
}
